name: CI/CD - OIDC S3 Upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_to_s3:
    environment: environment-pipelines
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
      BUCKET: ${{ vars.S3_BUCKET_NAME }}
      PREFIX: ${{ vars.S3_PREFIX }}
      SECRET_DATA: ${{ secrets.MY_S3_SECRET_DATA }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }} 
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-s3-upload-session

      - name: Create Artifact File
        id: create_file
        run: |
          TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
          RUN_ID=${{ github.run_id }}
          COMMIT_SHA=${{ github.sha }}

          CONTENT="Deployment Artifact Generated via GitHub Actions\n"
          CONTENT+="---------------------------------------------------\n"
          CONTENT+="Date/Time: ${TIMESTAMP}\n"
          CONTENT+="Run ID: ${RUN_ID}\n"
          CONTENT+="Commit SHA: ${COMMIT_SHA}\n"
          CONTENT+="Branch: ${{ github.ref_name }}\n"
          CONTENT+="Environment Secret Value: ${{ env.SECRET_DATA }}\n" # <-- Imprime: SiVesEstaVariableFuncionaBien
          
          FILE_NAME="deployment-artifact-${TIMESTAMP}.txt"
          echo -e "$CONTENT" > "$FILE_NAME"

          echo "ARTIFACT_FILE=$FILE_NAME" >> $GITHUB_OUTPUT

      - name: Upload Artifact to S3
        run: |
          aws s3 cp ${{ steps.create_file.outputs.ARTIFACT_FILE }} \
          s3://${{ env.BUCKET }}/${{ env.PREFIX }}/${{ steps.create_file.outputs.ARTIFACT_FILE }}
        env:
          AWS_PAGER: ""